package com.gao.jin.po;

import java.io.Serializable;
import java.util.Date;

public class TUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbg.generated
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_type
     *
     * @mbg.generated
     */
    private Byte user_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.locked
     *
     * @mbg.generated
     */
    private Byte locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.credit
     *
     * @mbg.generated
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_visit
     *
     * @mbg.generated
     */
    private Date last_visit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.last_ip
     *
     * @mbg.generated
     */
    private String last_ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param user_name the value for t_user.user_name
     *
     * @mbg.generated
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_type
     *
     * @return the value of t_user.user_type
     *
     * @mbg.generated
     */
    public Byte getUser_type() {
        return user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_type
     *
     * @param user_type the value for t_user.user_type
     *
     * @mbg.generated
     */
    public void setUser_type(Byte user_type) {
        this.user_type = user_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.locked
     *
     * @return the value of t_user.locked
     *
     * @mbg.generated
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.locked
     *
     * @param locked the value for t_user.locked
     *
     * @mbg.generated
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.credit
     *
     * @return the value of t_user.credit
     *
     * @mbg.generated
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.credit
     *
     * @param credit the value for t_user.credit
     *
     * @mbg.generated
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_visit
     *
     * @return the value of t_user.last_visit
     *
     * @mbg.generated
     */
    public Date getLast_visit() {
        return last_visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_visit
     *
     * @param last_visit the value for t_user.last_visit
     *
     * @mbg.generated
     */
    public void setLast_visit(Date last_visit) {
        this.last_visit = last_visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.last_ip
     *
     * @return the value of t_user.last_ip
     *
     * @mbg.generated
     */
    public String getLast_ip() {
        return last_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.last_ip
     *
     * @param last_ip the value for t_user.last_ip
     *
     * @mbg.generated
     */
    public void setLast_ip(String last_ip) {
        this.last_ip = last_ip == null ? null : last_ip.trim();
    }
}