server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student
    username: root
    password: gaojinsuo0628
    driver-class-name: com.mysql.jdbc.Driver
    #初始连接个数
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小x
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    type: com.alibaba.druid.pool.DruidDataSource

  quartz:

  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    port: 5672
    virtual-host: /





