package com.gao.jin.mapper;

import com.gao.jin.po.TUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_user (id, user_name, ",
        "`password`, user_type, ",
        "locked, credit, ",
        "last_visit, last_ip)",
        "values (#{id,jdbcType=INTEGER}, #{user_name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{user_type,jdbcType=TINYINT}, ",
        "#{locked,jdbcType=TINYINT}, #{credit,jdbcType=INTEGER}, ",
        "#{last_visit,jdbcType=TIMESTAMP}, #{last_ip,jdbcType=VARCHAR})"
    })
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=TUserSqlProvider.class, method="insertSelective")
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user_name, `password`, user_type, locked, credit, last_visit, last_ip",
        "from t_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="user_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_type", property="user_type", jdbcType=JdbcType.TINYINT),
        @Result(column="locked", property="locked", jdbcType=JdbcType.TINYINT),
        @Result(column="credit", property="credit", jdbcType=JdbcType.INTEGER),
        @Result(column="last_visit", property="last_visit", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="last_ip", property="last_ip", jdbcType=JdbcType.VARCHAR)
    })
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    @Update({
        "update t_user",
        "set user_name = #{user_name,jdbcType=VARCHAR},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "user_type = #{user_type,jdbcType=TINYINT},",
          "locked = #{locked,jdbcType=TINYINT},",
          "credit = #{credit,jdbcType=INTEGER},",
          "last_visit = #{last_visit,jdbcType=TIMESTAMP},",
          "last_ip = #{last_ip,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TUser record);
}